version: "3"
services:
  wikijs:
    image: requarks/wiki
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=tanaka
      - DB_PASS=p@ssword
      - DB_NAME=wikijs_db
    ports:
      - 3000:3000
    command: sh -c 'sleep 60; node server'
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=wikijs_db
      - MYSQL_USER=tanaka
      - MYSQL_PASSWORD=p@ssword
      - MYSQL_ROOT_PASSWORD=p@ssword
      - TZ=Asia/Tokyo
    ports:
      - 3306


volumes:
  db-store:

